# {{projectName}}

A semantic search API powered by Voyage AI embeddings and MongoDB Atlas Vector Search.

## Configuration

| Setting | Value |
|---------|-------|
| Embedding Model | `{{model}}` |
| Dimensions | {{dimensions}} |
| Database | `{{db}}` |
| Collection | `{{collection}}` |
| Vector Index | `{{index}}` |
{{#if rerank}}
| Rerank Model | `{{rerankModel}}` |
{{/if}}

## Setup

### 1. Create virtual environment

```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
```

### 2. Install dependencies

```bash
pip install -r requirements.txt
```

### 3. Configure environment

Copy `.env.example` to `.env` and fill in your credentials:

```bash
cp .env.example .env
```

Required variables:
- `VOYAGE_API_KEY` - Your Voyage AI API key from [dash.voyageai.com](https://dash.voyageai.com)
- `MONGODB_URI` - Your MongoDB Atlas connection string

### 4. Create vector index

In MongoDB Atlas, create a vector search index on your collection:

```json
{
  "fields": [
    {
      "type": "vector",
      "path": "{{field}}",
      "numDimensions": {{dimensions}},
      "similarity": "cosine"
    }
  ]
}
```

Name the index `{{index}}`.

### 5. Start the server

```bash
python app.py

# For production
gunicorn -w 4 -b 0.0.0.0:3000 app:app
```

## API Endpoints

### POST /api/search

Search for relevant documents.

```bash
curl -X POST http://localhost:3000/api/search \
  -H "Content-Type: application/json" \
  -d '{"query": "How does vector search work?", "limit": 5}'
```

Response:
```json
{
  "results": [
    {
      "text": "Vector search uses...",
      "score": 0.95,
      "metadata": {"source": "docs/guide.md"}
    }
  ],
  "meta": {
    "model": "{{model}}",
    "took": 123
  }
}
```

### POST /api/ingest

Ingest text documents.

```bash
curl -X POST http://localhost:3000/api/ingest \
  -H "Content-Type: application/json" \
  -d '{"text": "Your document content...", "metadata": {"source": "api"}}'
```

### GET /api/health

Check API health and database connection.

```bash
curl http://localhost:3000/api/health
```

## Project Structure

```
{{projectName}}/
├── app.py              # Flask application
├── voyage_client.py    # Voyage AI API client
├── mongo_client.py     # MongoDB connection helper
├── chunker.py          # Text chunking utilities
├── requirements.txt
├── .env.example
└── README.md
```

## Chunking Configuration

Documents are chunked with the following settings:

| Setting | Value |
|---------|-------|
| Strategy | `{{chunkStrategy}}` |
| Chunk Size | {{chunkSize}} characters |
| Overlap | {{chunkOverlap}} characters |

---

Generated by [vai](https://github.com/mrlynn/voyageai-cli) v{{vaiVersion}}
