/**
 * Semantic Search API
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 * 
 * Express router with endpoints:
 * - POST /api/search - Semantic search
 * - POST /api/ingest - Document ingestion
 * - GET /api/health - Health check
 */

const express = require('express');
const { retrieve, formatContext } = require('./retrieval');
const { ingestFile, ingestDirectory } = require('./ingest');
const { connect, close } = require('./connection');

const router = express.Router();

/**
 * POST /api/search
 * 
 * Request body:
 * {
 *   "query": "What is vector search?",
 *   "limit": 5,
 *   "includeContext": true
 * }
 * 
 * Response:
 * {
 *   "results": [...],
 *   "context": "...",
 *   "meta": { "model": "...", "took": 123 }
 * }
 */
router.post('/search', async (req, res) => {
  const start = Date.now();
  
  try {
    const { query, limit = 5, includeContext = false, filter } = req.body;
    
    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Query is required' });
    }
    
    const results = await retrieve(query, { limit, filter });
    
    const response = {
      results: results.map(r => ({
        text: r.text,
        score: r.score,
        metadata: r.metadata,
      })),
      meta: {
        model: '{{model}}',
{{#if rerank}}
        rerankModel: '{{rerankModel}}',
{{/if}}
        took: Date.now() - start,
      },
    };
    
    if (includeContext) {
      response.context = formatContext(results);
    }
    
    res.json(response);
  } catch (err) {
    console.error('Search error:', err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/ingest
 * 
 * Request body (for text):
 * {
 *   "text": "Document content...",
 *   "metadata": { "source": "api", "title": "..." }
 * }
 * 
 * Request body (for file path):
 * {
 *   "path": "./docs/guide.md"
 * }
 */
router.post('/ingest', async (req, res) => {
  const start = Date.now();
  
  try {
    const { text, metadata, path: filePath } = req.body;
    
    if (filePath) {
      const result = await ingestFile(filePath);
      return res.json({
        success: true,
        ...result,
        took: Date.now() - start,
      });
    }
    
    if (!text || typeof text !== 'string') {
      return res.status(400).json({ error: 'Text or path is required' });
    }
    
    // For API-provided text, we need to chunk, embed, and store inline
    const { embed } = require('./client');
    const { insertDocuments } = require('./connection');
    const { chunkText } = require('./ingest');
    
    const chunks = chunkText(text);
    const { embeddings, usage } = await embed(chunks, { inputType: 'document' });
    
    const documents = chunks.map((chunk, i) => ({
      text: chunk,
      embedding: embeddings[i],
      metadata: {
        ...metadata,
        source: 'api',
        chunkIndex: i,
        totalChunks: chunks.length,
      },
    }));
    
    await insertDocuments(documents);
    
    res.json({
      success: true,
      chunks: chunks.length,
      tokens: usage.total_tokens,
      took: Date.now() - start,
    });
  } catch (err) {
    console.error('Ingest error:', err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/health
 */
router.get('/health', async (req, res) => {
  try {
    await connect();
    res.json({
      status: 'healthy',
      model: '{{model}}',
      database: '{{db}}',
      collection: '{{collection}}',
    });
  } catch (err) {
    res.status(503).json({
      status: 'unhealthy',
      error: err.message,
    });
  }
});

module.exports = router;

// Standalone server if run directly
if (require.main === module) {
  const app = express();
  app.use(express.json());
  app.use('/api', router);
  
  const PORT = process.env.PORT || 3000;
  
  app.listen(PORT, () => {
    console.log(`Search API running on http://localhost:${PORT}`);
    console.log(`  POST /api/search  - Semantic search`);
    console.log(`  POST /api/ingest  - Document ingestion`);
    console.log(`  GET  /api/health  - Health check`);
  });
}
