/**
 * Branded footer
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import { Box, Typography, Link, Stack, Divider } from '@mui/material';

export default function Footer() {
  return (
    <Box component="footer" sx={{ mt: 'auto', pt: 6, pb: 4 }}>
      <Divider sx={{ mb: 3 }} />
      <Stack
        direction={{ xs: 'column', sm: 'row' }}
        justifyContent="space-between"
        alignItems="center"
        spacing={1}
        sx={{ px: 3 }}
      >
        <Typography variant="caption" color="text.secondary">
          Built with{' '}
          <Link
            href="https://github.com/mrlynn/voyageai-cli"
            target="_blank"
            rel="noopener"
            underline="hover"
            color="primary"
            fontWeight={600}
          >
            vai
          </Link>
          {' '}· Powered by{' '}
          <Link href="https://www.voyageai.com" target="_blank" rel="noopener" underline="hover" color="inherit">
            Voyage AI
          </Link>
          {' '}+{' '}
          <Link href="https://www.mongodb.com/atlas/search" target="_blank" rel="noopener" underline="hover" color="inherit">
            MongoDB Atlas Vector Search
          </Link>
        </Typography>

        <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace', fontSize: '0.65rem' }}>
          v{{vaiVersion}}
        </Typography>
      </Stack>
    </Box>
  );
}
