/**
 * Voyage AI API Client (Next.js)
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 * 
 * Model: {{model}}
 * Dimensions: {{dimensions}}
 */

function getApiUrl() {
  return process.env.VOYAGE_API_URL || 'https://api.voyageai.com/v1';
}

function getApiKey() {
  const key = process.env.VOYAGE_API_KEY;
  if (!key) throw new Error('VOYAGE_API_KEY environment variable is required');
  return key;
}

/**
 * Generate embeddings for text(s) using Voyage AI.
 */
export async function embed(input, options = {}) {
  const VOYAGE_API_URL = getApiUrl();
  const VOYAGE_API_KEY = getApiKey();

  const texts = Array.isArray(input) ? input : [input];
  
  const response = await fetch(`${VOYAGE_API_URL}/embeddings`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${VOYAGE_API_KEY}`,
    },
    body: JSON.stringify({
      model: options.model || '{{model}}',
      input: texts,
      input_type: options.inputType || '{{inputType}}',
      output_dimension: options.outputDimension || {{dimensions}},
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Voyage AI API error: ${response.status} ${error}`);
  }

  const data = await response.json();
  return {
    embeddings: data.data.map(d => d.embedding),
    usage: data.usage,
  };
}

/**
 * Embed a single query.
 */
export async function embedQuery(query, options = {}) {
  const result = await embed(query, { ...options, inputType: 'query' });
  return result.embeddings[0];
}

/**
 * Embed multiple documents.
 */
export async function embedDocuments(documents, options = {}) {
  const result = await embed(documents, { ...options, inputType: 'document' });
  return result.embeddings;
}

{{#if rerank}}
/**
 * Rerank documents by relevance to a query.
 */
export async function rerank(query, documents, options = {}) {
  const VOYAGE_API_URL = getApiUrl();
  const VOYAGE_API_KEY = getApiKey();

  const response = await fetch(`${VOYAGE_API_URL}/rerank`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${VOYAGE_API_KEY}`,
    },
    body: JSON.stringify({
      model: options.model || '{{rerankModel}}',
      query,
      documents,
      top_k: options.topK,
      return_documents: true,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Voyage AI rerank error: ${response.status} ${error}`);
  }

  const data = await response.json();
  return {
    results: data.data.map(d => ({
      index: d.index,
      relevanceScore: d.relevance_score,
      document: d.document,
    })),
    usage: data.usage,
  };
}
{{/if}}
