/**
 * MongoDB Connection Helper (Next.js)
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 * 
 * Uses connection caching for serverless environments.
 */

import { MongoClient } from 'mongodb';

function getUri() {
  const uri = process.env.MONGODB_URI;
  if (!uri) throw new Error('MONGODB_URI environment variable is required');
  return uri;
}

// Cache the client promise for connection reuse in serverless
let cached = global.mongo;

if (!cached) {
  cached = global.mongo = { conn: null, promise: null };
}

/**
 * Get a cached MongoDB client connection.
 * Reuses existing connection in serverless environment.
 */
export async function getMongoClient() {
  if (cached.conn) {
    return cached.conn;
  }

  if (!cached.promise) {
    cached.promise = MongoClient.connect(getUri());
  }

  cached.conn = await cached.promise;
  return cached.conn;
}

/**
 * Get the database instance.
 */
export async function getDb() {
  const client = await getMongoClient();
  return client.db('{{db}}');
}

/**
 * Get the documents collection.
 */
export async function getCollection() {
  const db = await getDb();
  return db.collection('{{collection}}');
}

/**
 * Perform a vector search.
 */
export async function vectorSearch(embedding, options = {}) {
  const collection = await getCollection();
  const limit = options.limit || 10;
  const numCandidates = options.numCandidates || limit * 10;

  const pipeline = [
    {
      $vectorSearch: {
        index: '{{index}}',
        path: '{{field}}',
        queryVector: embedding,
        numCandidates,
        limit,
      },
    },
    {
      $project: {
        _id: 1,
        text: 1,
        metadata: 1,
        score: { $meta: 'vectorSearchScore' },
      },
    },
  ];

  if (options.filter) {
    pipeline[0].$vectorSearch.filter = options.filter;
  }

  const results = await collection.aggregate(pipeline).toArray();
  return results.map(doc => ({
    document: doc,
    score: doc.score,
  }));
}

/**
 * Insert documents with embeddings.
 */
export async function insertDocuments(docs) {
  const collection = await getCollection();
  
  const documents = docs.map(doc => ({
    text: doc.text,
    {{field}}: doc.embedding,
    metadata: doc.metadata || {},
    _embeddedAt: new Date(),
    _model: '{{model}}',
  }));

  const result = await collection.insertMany(documents);
  return { insertedCount: result.insertedCount };
}
