/**
 * Branded AppBar with dark mode toggle
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import {
  AppBar,
  Toolbar,
  Typography,
  IconButton,
  Box,
  Chip,
  Tooltip,
  useTheme,
} from '@mui/material';
import DarkModeIcon from '@mui/icons-material/DarkMode';
import LightModeIcon from '@mui/icons-material/LightMode';
import GitHubIcon from '@mui/icons-material/GitHub';
import { useColorMode } from './ThemeRegistry';

export default function Navbar() {
  const theme = useTheme();
  const { mode, toggle } = useColorMode();

  return (
    <AppBar position="sticky" elevation={0} color="transparent">
      <Toolbar sx={{ gap: 1.5 }}>
        {/* Logo / wordmark */}
        <Box
          component="img"
          src="/vai-logo.png"
          alt="vai logo"
          sx={{ height: 28, width: 28 }}
        />
        <Typography
          variant="h6"
          sx={{
            fontWeight: 800,
            letterSpacing: '-0.02em',
            background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.primary.dark} 100%)`,
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
          }}
        >
          {{projectName}}
        </Typography>

        <Chip
          label="vai"
          size="small"
          sx={{
            fontWeight: 700,
            fontSize: '0.65rem',
            height: 20,
            bgcolor: 'primary.main',
            color: 'primary.contrastText',
          }}
        />

        <Box sx={{ flex: 1 }} />

        {/* Model badge */}
        <Chip
          label="{{model}}"
          size="small"
          variant="outlined"
          sx={{
            display: { xs: 'none', sm: 'flex' },
            fontFamily: 'monospace',
            fontSize: '0.7rem',
          }}
        />

        {/* GitHub link */}
        <Tooltip title="View on GitHub">
          <IconButton
            size="small"
            href="https://github.com/mrlynn/voyageai-cli"
            target="_blank"
            rel="noopener"
            sx={{ color: 'text.secondary' }}
          >
            <GitHubIcon fontSize="small" />
          </IconButton>
        </Tooltip>

        {/* Dark mode toggle */}
        <Tooltip title={mode === 'dark' ? 'Light mode' : 'Dark mode'}>
          <IconButton size="small" onClick={toggle} sx={{ color: 'text.secondary' }}>
            {mode === 'dark' ? <LightModeIcon fontSize="small" /> : <DarkModeIcon fontSize="small" />}
          </IconButton>
        </Tooltip>
      </Toolbar>
    </AppBar>
  );
}
