/**
 * Search Page — branded semantic search UI
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import { useState } from 'react';
import {
  Box,
  Container,
  TextField,
  Button,
  Card,
  CardContent,
  Typography,
  Chip,
  CircularProgress,
  Alert,
  InputAdornment,
  Stack,
  LinearProgress,
  Tooltip,
  IconButton,
  Fade,
  useTheme,
  alpha,
} from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

function ScoreBar({ score }) {
  const pct = Math.round(score * 100);
  const color = pct >= 80 ? 'success' : pct >= 50 ? 'primary' : 'warning';
  return (
    <Tooltip title={`Relevance: ${score.toFixed(4)}`}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, minWidth: 120 }}>
        <LinearProgress
          variant="determinate"
          value={pct}
          color={color}
          sx={{ flex: 1, height: 6, borderRadius: 3 }}
        />
        <Typography variant="caption" fontWeight={700} sx={{ fontFamily: 'monospace', minWidth: 36 }}>
          {pct}%
        </Typography>
      </Box>
    </Tooltip>
  );
}

export default function SearchPage() {
  const theme = useTheme();
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [meta, setMeta] = useState(null);
  const [copied, setCopied] = useState(null);

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    setError(null);

    try {
      const response = await fetch('/api/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query, limit: 5 }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Search failed');
      }

      const data = await response.json();
      setResults(data.results);
      setMeta(data.meta);
    } catch (err) {
      setError(err.message);
      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  const copyText = (text, idx) => {
    navigator.clipboard.writeText(text);
    setCopied(idx);
    setTimeout(() => setCopied(null), 1500);
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <Navbar />

      <Container maxWidth="md" sx={{ py: 5, flex: 1 }}>
        {/* Header */}
        <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 1 }}>
          <IconButton href="/" size="small" sx={{ color: 'text.secondary' }}>
            <ArrowBackIcon fontSize="small" />
          </IconButton>
          <Typography variant="h4" component="h1" fontWeight={800}>
            Semantic Search
          </Typography>
        </Stack>

        <Typography variant="subtitle1" sx={{ mb: 4, pl: 5.5 }}>
          Using <strong>{{model}}</strong> embeddings{{#if rerank}} with <strong>{{rerankModel}}</strong> reranking{{/if}}
        </Typography>

        {/* Search form */}
        <Box component="form" onSubmit={handleSearch} sx={{ mb: 4 }}>
          <TextField
            fullWidth
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Ask a question in natural language…"
            variant="outlined"
            autoFocus
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon sx={{ color: 'primary.main' }} />
                </InputAdornment>
              ),
              endAdornment: (
                <InputAdornment position="end">
                  <Button
                    type="submit"
                    variant="contained"
                    disabled={loading || !query.trim()}
                    sx={{ minWidth: 100 }}
                  >
                    {loading ? <CircularProgress size={22} color="inherit" /> : 'Search'}
                  </Button>
                </InputAdornment>
              ),
              sx: { pr: 1 },
            }}
          />
        </Box>

        {/* Error */}
        {error && (
          <Alert severity="error" sx={{ mb: 3, borderRadius: 2 }}>
            {error}
          </Alert>
        )}

        {/* Meta chips */}
        {meta && (
          <Stack direction="row" spacing={1} sx={{ mb: 3 }} flexWrap="wrap">
            <Chip label={`${results.length} results`} size="small" color="primary" />
            <Chip label={`${meta.took} ms`} size="small" variant="outlined" />
            <Chip label={meta.model} size="small" variant="outlined" sx={{ fontFamily: 'monospace', fontSize: '0.7rem' }} />
            {{#if rerank}}
            <Chip label={`reranked: ${meta.rerankModel}`} size="small" color="success" sx={{ fontFamily: 'monospace', fontSize: '0.7rem' }} />
            {{/if}}
          </Stack>
        )}

        {/* Results */}
        <Stack spacing={2}>
          {results.map((result, index) => (
            <Fade in key={index} timeout={200 + index * 80}>
              <Card>
                <CardContent sx={{ p: 3, '&:last-child': { pb: 3 } }}>
                  <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 1.5 }}>
                    <Stack direction="row" alignItems="center" spacing={1}>
                      <Chip
                        label={`#${index + 1}`}
                        size="small"
                        sx={{
                          fontWeight: 700,
                          bgcolor: alpha(theme.palette.primary.main, 0.1),
                          color: 'primary.dark',
                        }}
                      />
                      {result.metadata?.source && (
                        <Typography variant="caption" color="text.secondary" fontFamily="monospace">
                          {result.metadata.source}
                        </Typography>
                      )}
                    </Stack>
                    <ScoreBar score={result.score} />
                  </Stack>

                  <Typography
                    variant="body2"
                    sx={{
                      whiteSpace: 'pre-wrap',
                      lineHeight: 1.7,
                      color: 'text.primary',
                    }}
                  >
                    {result.text}
                  </Typography>

                  <Stack direction="row" justifyContent="flex-end" sx={{ mt: 1.5 }}>
                    <Tooltip title={copied === index ? 'Copied!' : 'Copy text'}>
                      <IconButton size="small" onClick={() => copyText(result.text, index)}>
                        <ContentCopyIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>
                  </Stack>
                </CardContent>
              </Card>
            </Fade>
          ))}
        </Stack>

        {/* Empty state */}
        {results.length === 0 && !loading && query && !error && (
          <Box sx={{ textAlign: 'center', py: 8 }}>
            <Typography variant="h6" color="text.secondary" gutterBottom>
              No results found
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Try rephrasing your query or ingest some documents first.
            </Typography>
          </Box>
        )}

        {/* Initial state */}
        {!meta && !loading && !error && (
          <Box sx={{ textAlign: 'center', py: 8 }}>
            <SearchIcon sx={{ fontSize: 48, color: 'text.disabled', mb: 2 }} />
            <Typography variant="h6" color="text.secondary" gutterBottom>
              Start searching
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Enter a natural-language query to find semantically similar documents.
            </Typography>
          </Box>
        )}
      </Container>

      <Footer />
    </Box>
  );
}
