/**
 * Landing Page — branded hero with quick stats
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import {
  Box,
  Container,
  Typography,
  Button,
  Grid,
  Card,
  CardContent,
  Stack,
  Chip,
  useTheme,
  alpha,
} from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import StorageIcon from '@mui/icons-material/Storage';
import BoltIcon from '@mui/icons-material/Bolt';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const features = [
  {
    icon: <AutoAwesomeIcon />,
    title: 'Voyage AI Embeddings',
    desc: 'State-of-the-art {{model}} model with {{dimensions}}-dimensional vectors for precise semantic understanding.',
  },
  {
    icon: <StorageIcon />,
    title: 'MongoDB Atlas Vector Search',
    desc: 'Lightning-fast approximate nearest-neighbor search on your {{db}}.{{collection}} collection.',
  },
  {
    icon: <BoltIcon />,
    title: 'Full RAG Pipeline',
    desc: 'Ingest, chunk, embed, store, and search — a complete retrieval-augmented generation stack out of the box.',
  },
];

export default function HomePage() {
  const theme = useTheme();

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <Navbar />

      {/* ── Hero ──────────────────────────────── */}
      <Box
        sx={{
          position: 'relative',
          overflow: 'hidden',
          pt: { xs: 8, md: 14 },
          pb: { xs: 8, md: 12 },
        }}
      >
        {/* gradient accent */}
        <Box
          sx={{
            position: 'absolute',
            top: -120,
            right: -120,
            width: 480,
            height: 480,
            borderRadius: '50%',
            background: `radial-gradient(circle, ${alpha(theme.palette.primary.main, 0.15)} 0%, transparent 70%)`,
            pointerEvents: 'none',
          }}
        />

        <Container maxWidth="md" sx={{ position: 'relative', textAlign: 'center' }}>
          <Box
            component="img"
            src="/vai-logo.png"
            alt="vai logo"
            sx={{ width: 64, height: 64, mb: 2, mx: 'auto', display: 'block' }}
          />

          <Chip
            label="Scaffolded with vai"
            size="small"
            color="success"
            sx={{ mb: 3 }}
          />

          <Typography variant="h2" component="h1" gutterBottom>
            <Box
              component="span"
              sx={{
                background: `linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.primary.light})`,
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              {{projectName}}
            </Box>
          </Typography>

          <Typography variant="h5" component="p" color="text.secondary" gutterBottom>
            Semantic search powered by Voyage AI
          </Typography>

          <Typography
            variant="h6"
            color="text.secondary"
            sx={{ maxWidth: 560, mx: 'auto', mb: 4, fontWeight: 400 }}
          >
            Ask questions in natural language and find the most relevant documents
            using vector embeddings{{#if rerank}} with reranking{{/if}}.
          </Typography>

          <Stack direction="row" spacing={2} justifyContent="center">
            <Button
              variant="contained"
              size="large"
              href="/search"
              startIcon={<SearchIcon />}
              sx={{ px: 4 }}
            >
              Try Search
            </Button>
            <Button
              variant="outlined"
              size="large"
              href="/api/health"
              sx={{ px: 4 }}
            >
              API Health
            </Button>
          </Stack>
        </Container>
      </Box>

      {/* ── Feature cards ────────────────────── */}
      <Container maxWidth="lg" sx={{ pb: 10 }}>
        <Grid container spacing={3}>
          {features.map((f, i) => (
            <Grid item xs={12} md={4} key={i}>
              <Card sx={{ height: '100%' }}>
                <CardContent sx={{ p: 3 }}>
                  <Box
                    sx={{
                      width: 48,
                      height: 48,
                      borderRadius: 2,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      mb: 2,
                      bgcolor: alpha(theme.palette.primary.main, 0.1),
                      color: 'primary.main',
                    }}
                  >
                    {f.icon}
                  </Box>
                  <Typography variant="h6" gutterBottom>
                    {f.title}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    {f.desc}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>

        {/* ── Config overview ────────────────── */}
        <Box
          sx={{
            mt: 6,
            p: 3,
            borderRadius: 3,
            bgcolor: theme.palette.mode === 'dark' ? 'rgba(255,255,255,0.03)' : 'grey.50',
            border: `1px solid ${theme.palette.divider}`,
          }}
        >
          <Typography variant="overline" color="text.secondary" gutterBottom>
            Configuration
          </Typography>
          <Stack direction="row" flexWrap="wrap" gap={1} sx={{ mt: 1 }}>
            <Chip label="Model: {{model}}" size="small" variant="outlined" sx={{ fontFamily: 'monospace' }} />
            <Chip label="Dims: {{dimensions}}" size="small" variant="outlined" sx={{ fontFamily: 'monospace' }} />
            <Chip label="DB: {{db}}.{{collection}}" size="small" variant="outlined" sx={{ fontFamily: 'monospace' }} />
            <Chip label="Index: {{index}}" size="small" variant="outlined" sx={{ fontFamily: 'monospace' }} />
            {{#if rerank}}
            <Chip label="Rerank: {{rerankModel}}" size="small" color="success" sx={{ fontFamily: 'monospace' }} />
            {{/if}}
          </Stack>
        </Box>
      </Container>

      <Footer />
    </Box>
  );
}
