/**
 * Search Page (MUI)
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import { useState } from 'react';
import {
  Box,
  Container,
  TextField,
  Button,
  Card,
  CardContent,
  Typography,
  List,
  ListItem,
  Chip,
  CircularProgress,
  Alert,
  InputAdornment,
} from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';

export default function SearchPage() {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [meta, setMeta] = useState(null);

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    setError(null);

    try {
      const response = await fetch('/api/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query, limit: 5 }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Search failed');
      }

      const data = await response.json();
      setResults(data.results);
      setMeta(data.meta);
    } catch (err) {
      setError(err.message);
      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Typography variant="h4" component="h1" gutterBottom>
        Semantic Search
      </Typography>
      
      <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
        Search your documents using {{model}} embeddings
        {{#if rerank}} with {{rerankModel}} reranking{{/if}}.
      </Typography>

      <Box component="form" onSubmit={handleSearch} sx={{ mb: 4 }}>
        <TextField
          fullWidth
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Enter your search query..."
          variant="outlined"
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <SearchIcon />
              </InputAdornment>
            ),
            endAdornment: (
              <InputAdornment position="end">
                <Button
                  type="submit"
                  variant="contained"
                  disabled={loading || !query.trim()}
                >
                  {loading ? <CircularProgress size={24} /> : 'Search'}
                </Button>
              </InputAdornment>
            ),
          }}
        />
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {meta && (
        <Box sx={{ mb: 2, display: 'flex', gap: 1 }}>
          <Chip label={`${results.length} results`} size="small" />
          <Chip label={`${meta.took}ms`} size="small" variant="outlined" />
          <Chip label={meta.model} size="small" variant="outlined" />
        </Box>
      )}

      <List>
        {results.map((result, index) => (
          <ListItem key={index} sx={{ px: 0 }}>
            <Card sx={{ width: '100%' }}>
              <CardContent>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                  <Typography variant="subtitle2" color="text.secondary">
                    {result.metadata?.source || 'Document'}
                  </Typography>
                  <Chip
                    label={`Score: ${result.score.toFixed(3)}`}
                    size="small"
                    color={result.score > 0.8 ? 'success' : 'default'}
                  />
                </Box>
                <Typography variant="body2" sx={{ whiteSpace: 'pre-wrap' }}>
                  {result.text}
                </Typography>
              </CardContent>
            </Card>
          </ListItem>
        ))}
      </List>

      {results.length === 0 && !loading && query && !error && (
        <Typography color="text.secondary" align="center">
          No results found for "{query}"
        </Typography>
      )}
    </Container>
  );
}
