# {{projectName}}

A semantic search application powered by Voyage AI embeddings, MongoDB Atlas Vector Search, and Next.js with Material UI.

## Configuration

| Setting | Value |
|---------|-------|
| Embedding Model | `{{model}}` |
| Dimensions | {{dimensions}} |
| Database | `{{db}}` |
| Collection | `{{collection}}` |
| Vector Index | `{{index}}` |
{{#if rerank}}
| Rerank Model | `{{rerankModel}}` |
{{/if}}

## Setup

### 1. Install dependencies

```bash
npm install
```

### 2. Configure environment

Copy `.env.example` to `.env.local` and fill in your credentials:

```bash
cp .env.example .env.local
```

Required variables:
- `VOYAGE_API_KEY` - Your Voyage AI API key from [dash.voyageai.com](https://dash.voyageai.com)
- `MONGODB_URI` - Your MongoDB Atlas connection string

### 3. Create vector index

In MongoDB Atlas, create a vector search index on your collection:

```json
{
  "fields": [
    {
      "type": "vector",
      "path": "{{field}}",
      "numDimensions": {{dimensions}},
      "similarity": "cosine"
    }
  ]
}
```

Name the index `{{index}}`.

### 4. Start the development server

```bash
npm run dev
```

Open [http://localhost:3000](http://localhost:3000) to see the search interface.

## Project Structure

```
{{projectName}}/
├── app/
│   ├── layout.jsx          # Root layout with MUI theme
│   ├── page.jsx            # Home page
│   ├── search/
│   │   └── page.jsx        # Search page (MUI)
│   └── api/
│       ├── search/route.js # Search endpoint
│       └── ingest/route.js # Ingest endpoint
├── lib/
│   ├── voyage.js           # Voyage AI client
│   ├── mongodb.js          # MongoDB connection
│   └── theme.js            # MUI theme
├── .env.example
├── package.json
└── README.md
```

## API Endpoints

### POST /api/search

```bash
curl -X POST http://localhost:3000/api/search \
  -H "Content-Type: application/json" \
  -d '{"query": "How does vector search work?", "limit": 5}'
```

### POST /api/ingest

```bash
curl -X POST http://localhost:3000/api/ingest \
  -H "Content-Type: application/json" \
  -d '{"text": "Your document content...", "metadata": {"source": "api"}}'
```

---

Generated by [vai](https://github.com/mrlynn/voyageai-cli) v{{vaiVersion}}
