/**
 * Ingest API Route Handler
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 * 
 * POST /api/ingest
 */

import { NextResponse } from 'next/server';
import { embed } from '@/lib/voyage';
import { insertDocuments } from '@/lib/mongodb';

/**
 * Chunk text using recursive splitting.
 */
function chunkText(text, size = {{chunkSize}}, overlap = {{chunkOverlap}}) {
  const separators = ['\n\n', '\n', '. ', ' '];
  
  function splitRecursive(text, sepIndex = 0) {
    if (text.length <= size) {
      const trimmed = text.trim();
      return trimmed ? [trimmed] : [];
    }
    
    if (sepIndex >= separators.length) {
      const chunks = [];
      let start = 0;
      while (start < text.length) {
        const chunk = text.slice(start, start + size).trim();
        if (chunk) chunks.push(chunk);
        start += size - overlap;
      }
      return chunks;
    }
    
    const separator = separators[sepIndex];
    const parts = text.split(separator);
    const chunks = [];
    let current = '';
    
    for (const part of parts) {
      const potential = current ? current + separator + part : part;
      if (potential.length <= size) {
        current = potential;
      } else {
        if (current) chunks.push(...splitRecursive(current, sepIndex + 1));
        current = part;
      }
    }
    
    if (current) chunks.push(...splitRecursive(current, sepIndex + 1));
    return chunks;
  }
  
  return splitRecursive(text);
}

export async function POST(request) {
  const start = Date.now();
  
  try {
    const body = await request.json();
    const { text, metadata = {} } = body;
    
    if (!text || typeof text !== 'string') {
      return NextResponse.json(
        { error: 'Text is required' },
        { status: 400 }
      );
    }
    
    // Chunk the text
    const chunks = chunkText(text);
    
    if (chunks.length === 0) {
      return NextResponse.json({
        success: true,
        chunks: 0,
        tokens: 0,
        took: Date.now() - start,
      });
    }
    
    // Embed all chunks
    const { embeddings, usage } = await embed(chunks, { inputType: 'document' });
    
    // Prepare documents
    const documents = chunks.map((chunk, i) => ({
      text: chunk,
      embedding: embeddings[i],
      metadata: {
        ...metadata,
        source: metadata.source || 'api',
        chunkIndex: i,
        totalChunks: chunks.length,
      },
    }));
    
    // Insert into MongoDB
    await insertDocuments(documents);
    
    return NextResponse.json({
      success: true,
      chunks: chunks.length,
      tokens: usage.total_tokens,
      took: Date.now() - start,
    });
  } catch (error) {
    console.error('Ingest error:', error);
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}
