/**
 * Theme Registry — light/dark toggle with localStorage persistence
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import { createContext, useContext, useMemo, useState, useEffect } from 'react';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { lightTheme, darkTheme } from '@/lib/theme';

const ColorModeContext = createContext({ toggle: () => {}, mode: 'light' });

export function useColorMode() {
  return useContext(ColorModeContext);
}

export function ThemeRegistry({ children }) {
  const [mode, setMode] = useState('light');

  useEffect(() => {
    const stored = localStorage.getItem('vai-color-mode');
    if (stored === 'dark' || stored === 'light') {
      setMode(stored);
    } else if (window.matchMedia?.('(prefers-color-scheme: dark)').matches) {
      setMode('dark');
    }
  }, []);

  const colorMode = useMemo(() => ({
    mode,
    toggle: () =>
      setMode((prev) => {
        const next = prev === 'light' ? 'dark' : 'light';
        localStorage.setItem('vai-color-mode', next);
        return next;
      }),
  }), [mode]);

  const theme = mode === 'dark' ? darkTheme : lightTheme;

  return (
    <ColorModeContext.Provider value={colorMode}>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        {children}
      </ThemeProvider>
    </ColorModeContext.Provider>
  );
}
