/**
 * MUI Theme Configuration
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import { createTheme } from '@mui/material/styles';

// MongoDB-inspired color palette
const palette = {
  primary: {
    main: '#00ED64',      // MongoDB Green
    light: '#4DFF94',
    dark: '#00B84A',
    contrastText: '#000',
  },
  secondary: {
    main: '#001E2B',      // MongoDB Dark
    light: '#1C3A4B',
    dark: '#000F17',
    contrastText: '#fff',
  },
  background: {
    default: '#FAFAFA',
    paper: '#FFFFFF',
  },
  text: {
    primary: '#001E2B',
    secondary: '#5C6C75',
  },
};

export const theme = createTheme({
  palette,
  typography: {
    fontFamily: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
    h1: {
      fontWeight: 700,
    },
    h2: {
      fontWeight: 600,
    },
    h3: {
      fontWeight: 600,
    },
    h4: {
      fontWeight: 600,
    },
  },
  shape: {
    borderRadius: 8,
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          textTransform: 'none',
          fontWeight: 600,
        },
        contained: {
          boxShadow: 'none',
          '&:hover': {
            boxShadow: 'none',
          },
        },
      },
    },
    MuiCard: {
      styleOverrides: {
        root: {
          boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.06)',
        },
      },
    },
    MuiChip: {
      styleOverrides: {
        root: {
          fontWeight: 500,
        },
      },
    },
  },
});
