/**
 * MUI Theme Configuration — vai branded
 * Generated by vai v{{vaiVersion}} on {{generatedAt}}
 */

'use client';

import { createTheme, responsiveFontSizes } from '@mui/material/styles';

/* ── colour tokens ─────────────────────────────── */
const brand = {
  green:      '#00ED64',
  greenLight: '#71F6A0',
  greenDark:  '#00B84A',
  navy:       '#001E2B',
  navyLight:  '#1C3A4B',
  slate:      '#3D4F58',
  mist:       '#E3FCF7',
  white:      '#FFFFFF',
  offWhite:   '#F9FBFA',
  grey100:    '#F5F6F7',
  grey300:    '#C1C7C6',
  grey500:    '#889397',
  grey700:    '#5C6C75',
};

/* ── light palette ─────────────────────────────── */
const lightPalette = {
  mode: 'light',
  primary:    { main: brand.green, light: brand.greenLight, dark: brand.greenDark, contrastText: brand.navy },
  secondary:  { main: brand.navy,  light: brand.navyLight,  dark: '#000F17',      contrastText: brand.white },
  background: { default: brand.offWhite, paper: brand.white },
  text:       { primary: brand.navy, secondary: brand.grey700 },
  divider:    brand.grey300,
  success:    { main: brand.greenDark },
};

/* ── dark palette ──────────────────────────────── */
const darkPalette = {
  mode: 'dark',
  primary:    { main: brand.green, light: brand.greenLight, dark: brand.greenDark, contrastText: brand.navy },
  secondary:  { main: '#90CAF9', light: '#BBDEFB', dark: '#42A5F5', contrastText: brand.navy },
  background: { default: '#0A1117', paper: '#111D27' },
  text:       { primary: '#E8EDDF', secondary: '#9AABB8' },
  divider:    'rgba(255,255,255,0.12)',
  success:    { main: brand.green },
};

function buildTheme(mode = 'light') {
  let theme = createTheme({
    palette: mode === 'dark' ? darkPalette : lightPalette,
    typography: {
      fontFamily: '"Inter", "IBM Plex Sans", "Roboto", "Helvetica Neue", Arial, sans-serif',
      h1: { fontWeight: 800, letterSpacing: '-0.02em' },
      h2: { fontWeight: 700, letterSpacing: '-0.01em' },
      h3: { fontWeight: 700 },
      h4: { fontWeight: 700 },
      h5: { fontWeight: 600 },
      h6: { fontWeight: 600 },
      subtitle1: { fontWeight: 500, color: mode === 'dark' ? '#9AABB8' : brand.grey700 },
      button: { fontWeight: 600, textTransform: 'none' },
      overline: { fontWeight: 700, letterSpacing: '0.08em' },
    },
    shape: { borderRadius: 12 },
    shadows: [
      'none',
      '0 1px 2px rgba(0,0,0,0.06)',
      '0 1px 4px rgba(0,0,0,0.08)',
      '0 2px 8px rgba(0,0,0,0.10)',
      '0 4px 12px rgba(0,0,0,0.10)',
      '0 6px 16px rgba(0,0,0,0.10)',
      ...Array(19).fill('0 8px 24px rgba(0,0,0,0.12)'),
    ],
    components: {
      MuiCssBaseline: {
        styleOverrides: {
          body: {
            scrollbarWidth: 'thin',
            '&::-webkit-scrollbar': { width: 6 },
            '&::-webkit-scrollbar-thumb': { background: brand.grey300, borderRadius: 3 },
          },
        },
      },
      MuiButton: {
        defaultProps: { disableElevation: true },
        styleOverrides: {
          root: { borderRadius: 8, padding: '8px 20px', fontWeight: 600 },
          containedPrimary: {
            color: brand.navy,
            '&:hover': { background: brand.greenLight },
          },
          outlined: { borderWidth: 2, '&:hover': { borderWidth: 2 } },
        },
      },
      MuiCard: {
        styleOverrides: {
          root: {
            borderRadius: 16,
            border: `1px solid ${mode === 'dark' ? 'rgba(255,255,255,0.08)' : brand.grey100}`,
            transition: 'box-shadow 0.2s ease, transform 0.2s ease',
            '&:hover': {
              boxShadow: mode === 'dark'
                ? '0 8px 24px rgba(0,237,100,0.08)'
                : '0 8px 24px rgba(0,0,0,0.08)',
              transform: 'translateY(-2px)',
            },
          },
        },
      },
      MuiChip: {
        styleOverrides: {
          root: { fontWeight: 600, borderRadius: 8 },
          colorSuccess: {
            background: mode === 'dark' ? 'rgba(0,237,100,0.15)' : brand.mist,
            color: mode === 'dark' ? brand.green : brand.greenDark,
          },
        },
      },
      MuiTextField: {
        styleOverrides: {
          root: {
            '& .MuiOutlinedInput-root': {
              borderRadius: 12,
              '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                borderColor: brand.green,
                borderWidth: 2,
              },
            },
          },
        },
      },
      MuiAppBar: {
        styleOverrides: {
          root: {
            background: mode === 'dark' ? '#0D1820' : brand.white,
            borderBottom: `1px solid ${mode === 'dark' ? 'rgba(255,255,255,0.08)' : brand.grey100}`,
          },
        },
      },
      MuiLinearProgress: {
        styleOverrides: {
          root: { borderRadius: 4, height: 6 },
          bar: { borderRadius: 4 },
        },
      },
    },
  });

  theme = responsiveFontSizes(theme);
  return theme;
}

export const lightTheme = buildTheme('light');
export const darkTheme  = buildTheme('dark');

/* default export for simple usage */
export const theme = lightTheme;
